In [47]:
import numpy as np
# For adv numerical computation based on array and matrix

In [48]:
l = [1, 2, 3, 4]

In [49]:
ar = np.array(l)
type(ar)

numpy.ndarray

In [50]:
np.array([[1, 2], [3,4]])

array([[1, 2],
       [3, 4]])

In [51]:
np.asarray(l)

array([1, 2, 3, 4])

In [52]:
a = [2, 3, 4]

In [53]:
np.asanyarray(a)

array([2, 3, 4])

In [54]:
b = np.matrix(l)

In [55]:
b
# matrix default to dimensional data return karega
# Matrix is sub class of array in np

matrix([[1, 2, 3, 4]])

In [56]:
np.asanyarray(b)
# Isliye array me nhi change kiya kyu ki matrix bhi ek type ka array hai

matrix([[1, 2, 3, 4]])

In [57]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [58]:
c = a
c

array([1, 2, 3, 4])

In [59]:
c[0] = 100

In [60]:
c

array([100,   2,   3,   4])

In [61]:
a
# c is swallow copy of a

array([100,   2,   3,   4])

In [62]:
d = np.copy(a)

In [63]:
a[1] = 20000
a

array([  100, 20000,     3,     4])

In [64]:
d
# Now d is not swallow copy of a, it is deep copy change done in a and d won't affect each other

array([100,   2,   3,   4])

In [65]:
# fromfunction help u to generate arrays at any time 
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [66]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [67]:
def test(x, y):
    return x*y

np.fromfunction(test, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [68]:
iterable = (i*i for i in range(5))

In [69]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [70]:
np.fromstring("12 334", sep=" ")

array([ 12., 334.])

In [71]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

Numpy - Data Types.

In [93]:
l = [2, 3, 5, 4, 9 ]

In [94]:
ar = np.array(l)

In [95]:
ar.ndim

1

In [96]:
ar2 = np.array([[1, 3, 4, 3,55], [2, 3, 4, 5, 6]])
ar2.ndim

2

In [97]:
ar2.size

10

In [98]:
ar2

array([[ 1,  3,  4,  3, 55],
       [ 2,  3,  4,  5,  6]])

In [101]:
ar.shape

(5,)

In [102]:
ar2.shape

(2, 5)

In [103]:
ar.dtype

dtype('int32')

In [104]:
ar2.dtype

dtype('int32')

In [106]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [107]:
ar22.dtype

dtype('float64')

In [108]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [109]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [110]:
np.arange(2.3, 5.6, .3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [111]:
list(np.arange(2.3, 5.6, .3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [112]:
# It will divide line in n equal space
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [113]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [115]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])