In [2]:
import numpy as np
# For adv numerical computation based on array and matrix

In [3]:
l = [1, 2, 3, 4]

In [4]:
ar = np.array(l)
type(ar)

numpy.ndarray

In [5]:
np.array([[1, 2], [3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
a = [2, 3, 4]

In [8]:
np.asanyarray(a)

array([2, 3, 4])

In [9]:
b = np.matrix(l)

In [10]:
b
# matrix default two dimensional data return karega
# Matrix is sub class of array in np

matrix([[1, 2, 3, 4]])

In [11]:
np.asanyarray(b)
# Isliye array me nhi change kiya kyu ki matrix bhi ek type ka array hai

matrix([[1, 2, 3, 4]])

In [12]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [13]:
c = a
c

array([1, 2, 3, 4])

In [14]:
c[0] = 100

In [15]:
c

array([100,   2,   3,   4])

In [16]:
a
# c is swallow copy of a

array([100,   2,   3,   4])

In [17]:
d = np.copy(a)

In [18]:
a[1] = 20000
a

array([  100, 20000,     3,     4])

In [19]:
d
# Now d is not swallow copy of a, it is deep copy change done in a and d won't affect each other

array([100,   2,   3,   4])

In [20]:
# fromfunction help u to generate arrays at any time 
np.fromfunction(lambda i, j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [21]:
np.fromfunction(lambda i, j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [22]:
def test(x, y):
    return x*y

np.fromfunction(test, (3,2))

array([[0., 0.],
       [0., 1.],
       [0., 2.]])

In [23]:
iterable = (i*i for i in range(5))

In [24]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [25]:
np.fromstring("12 334", sep=" ")

array([ 12., 334.])

In [26]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

Numpy - Data Types.

In [27]:
l = [2, 3, 5, 4, 9 ]

In [28]:
ar = np.array(l)

In [29]:
ar.ndim

1

In [30]:
ar2 = np.array([[1, 3, 4, 3,55], [2, 3, 4, 5, 6]])
ar2.ndim

2

In [31]:
ar2.size

10

In [32]:
ar2

array([[ 1,  3,  4,  3, 55],
       [ 2,  3,  4,  5,  6]])

In [33]:
ar.shape

(5,)

In [34]:
ar2.shape

(2, 5)

In [35]:
ar.dtype

dtype('int32')

In [36]:
ar2.dtype

dtype('int32')

In [37]:
ar22 = np.array([(1.4,45,45) , (23,45,66)])
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [38]:
ar22.dtype

dtype('float64')

In [39]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [40]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [41]:
np.arange(2.3, 5.6, .3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [42]:
list(np.arange(2.3, 5.6, .3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [43]:
# It will divide line in n equal space
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [48]:
ar4  = np.zeros((3, 4, 2, 3))
# We have 2*3 matrix four times and the whole three times
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [49]:
ar4.ndim

4

In [50]:
np.ones(4)

array([1., 1., 1., 1.])

In [51]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
on = np.ones((3, 2, 4))
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [54]:
on * 5

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [55]:
on + 1 

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [57]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
# Identity matrix
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
np.linspace(2, 4, 10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [64]:
np.logspace(2, 4, 10, base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [72]:
# Based on standard normal distribution data produce karta hai
arr = np.random.randn(3, 4)
arr

array([[-0.89323592,  1.89284098,  1.49051207, -0.93773277],
       [ 0.01359357,  0.20914351,  0.73954917, -1.08033228],
       [ 0.0587252 , -0.14663478, -0.84606754, -0.70010479]])

In [73]:
import pandas as pd

In [74]:
pd.DataFrame(arr)

0         1         2         3
0 -0.893236  1.892841  1.490512 -0.937733
1  0.013594  0.209144  0.739549 -1.080332
2  0.058725 -0.146635 -0.846068 -0.700105

In [75]:
np.random.rand(3, 4)
# generates a NumPy array arr with dimensions 3x4, filled with random values between 0 and 1. Each element in the array is independently 
# sampled from a uniform distribution over the interval [0, 1).

array([[0.67005702, 0.65964616, 0.4653667 , 0.23587634],
       [0.27467185, 0.54627768, 0.38619038, 0.52705569],
       [0.96243456, 0.11063202, 0.17376275, 0.91323964]])

In [79]:
pd.DataFrame(np.random.randint(1, 100, (300,300)))

0    1    2    3    4    5    6    7    8    9    ...  290  291  292  \
0      1   98    6   91   18   73   36   63   53   32  ...   91   24   93   
1     36   33   28   68   32   37   91   40   46   88  ...   40   23   51   
2     11   40   66   72   45   75   61   81   29   65  ...   30   69   40   
3     23   34   60   55   69   98   26   22   44   30  ...   65   97   94   
4     52   81   71   54   32   54   87   60   90   30  ...   51   47   21   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   54   12   73   31   95   17   24   20   39   70  ...   65   47   31   
296   12   68    3    5   97   41   79   28   33    7  ...   73   59   22   
297   74   39    4   15   40    8   32   73   83   94  ...   47   41    3   
298   46   27   50   24   22    2   96   17   74   10  ...   53   24   31   
299   79   12   62    1   38   36   34   26   59   73  ...   95   40   63   

     293  294  295  296  297  298  299  
0     97   28   49   66   39   67   93  
1     84   79   10   96   85   13   10  
2     50   61   63   91   35   58   73  
3     83   91   80   48   93   40   86  
4     74   28    5   92   69   53   68  
..   ...  ...  ...  ...  ...  ...  ...  
295   95   84   90   31   75   24   47  
296   63   24   31   32   44   93   88  
297   52   57   94   38   76    1   55  
298   37   30   51   32   10   12    9  
299   99   46   40   47    5   76   77  

[300 rows x 300 columns]

In [80]:
pd.DataFrame(np.random.randint(1, 100, (300,300))).to_csv("Test.csv")

In [96]:
arr = np.random.rand(3, 4)
arr.reshape(6, 2)


array([[0.81040994, 0.87509961],
       [0.61473668, 0.34723228],
       [0.23337915, 0.9258757 ],
       [0.5567028 , 0.79506073],
       [0.70664847, 0.03261895],
       [0.26634861, 0.43596499]])

In [97]:
arr1 =  arr.reshape(6, -222)
arr1

array([[0.81040994, 0.87509961],
       [0.61473668, 0.34723228],
       [0.23337915, 0.9258757 ],
       [0.5567028 , 0.79506073],
       [0.70664847, 0.03261895],
       [0.26634861, 0.43596499]])

In [99]:
arr1[1, 1]

0.34723227809097634

In [102]:
arr1[3, 1]

0.7950607282193376

In [103]:
arr1[1][1]

0.34723227809097634

In [104]:
arr1

array([[0.81040994, 0.87509961],
       [0.61473668, 0.34723228],
       [0.23337915, 0.9258757 ],
       [0.5567028 , 0.79506073],
       [0.70664847, 0.03261895],
       [0.26634861, 0.43596499]])

In [106]:
arr1[2:5, 1]

array([0.9258757 , 0.79506073, 0.03261895])

In [108]:
arr = np.random.randint(1, 100, (5, 5))
arr

array([[24, 60, 64, 44,  7],
       [95, 83,  7, 10, 79],
       [70, 68, 14, 38, 26],
       [31, 94,  6, 16, 72],
       [77, 40, 87, 56, 53]])

In [110]:
arr > 50

array([[False,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [ True,  True, False, False, False],
       [False,  True, False, False,  True],
       [ True, False,  True,  True,  True]])

In [111]:
arr[arr > 50]

array([60, 64, 95, 83, 79, 70, 68, 94, 72, 77, 87, 56, 53])

In [112]:
arr

array([[24, 60, 64, 44,  7],
       [95, 83,  7, 10, 79],
       [70, 68, 14, 38, 26],
       [31, 94,  6, 16, 72],
       [77, 40, 87, 56, 53]])

In [113]:
arr[2:4, 1:3]

array([[68, 14],
       [94,  6]])

In [115]:
arr[0, 0] = 1000
arr

array([[1000,   60,   64,   44,    7],
       [  95,   83,    7,   10,   79],
       [  70,   68,   14,   38,   26],
       [  31,   94,    6,   16,   72],
       [  77,   40,   87,   56,   53]])

In [118]:
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))
arr1

array([[2, 2, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [120]:
arr2

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [121]:
arr1 + arr2

array([[3, 4, 3],
       [4, 3, 3],
       [4, 4, 3]])

In [122]:
arr1 - arr2

array([[ 1,  0, -1],
       [ 0, -1, -1],
       [ 0,  0,  1]])

In [123]:
arr1 * arr2

array([[2, 4, 2],
       [4, 2, 2],
       [4, 4, 2]])

In [124]:
# Matrix multiplication
arr1 @ arr2

array([[ 8, 10,  9],
       [ 6,  8,  7],
       [10, 12, 10]])

In [125]:
arr1 / 0

C:\Users\shrey\AppData\Local\Temp\ipykernel_11004\824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [126]:
arr1 + 1

array([[3, 3, 2],
       [3, 2, 2],
       [3, 3, 3]])

In [127]:
arr2**2

array([[1, 4, 4],
       [4, 4, 4],
       [4, 4, 1]])

Numpy – Broadcasting.

In [130]:
arr = np.zeros((4,4))

In [133]:
row = np.array([1,2,3,4])
row.ndim

1

In [134]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [137]:
row.T

array([1, 2, 3, 4])

In [139]:
col = np.array([[1,2,3,4]])

In [140]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [141]:
arr + col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [145]:
arr2 = np.random.randint(1, 4, (3, 4))
arr2

array([[2, 3, 3, 1],
       [2, 3, 3, 2],
       [1, 3, 1, 1]])

In [146]:
np.sqrt(arr2)

array([[1.41421356, 1.73205081, 1.73205081, 1.        ],
       [1.41421356, 1.73205081, 1.73205081, 1.41421356],
       [1.        , 1.73205081, 1.        , 1.        ]])

In [147]:
np.exp(arr2)

array([[ 7.3890561 , 20.08553692, 20.08553692,  2.71828183],
       [ 7.3890561 , 20.08553692, 20.08553692,  7.3890561 ],
       [ 2.71828183, 20.08553692,  2.71828183,  2.71828183]])

In [148]:
np.log10(arr2)

array([[0.30103   , 0.47712125, 0.47712125, 0.        ],
       [0.30103   , 0.47712125, 0.47712125, 0.30103   ],
       [0.        , 0.47712125, 0.        , 0.        ]])