Numpy - Array Manipulation.

In [88]:
import numpy as np

In [89]:
arr = np.random.randint(1, 10, (3,4))
arr

array([[7, 5, 7, 9],
       [6, 3, 7, 4],
       [8, 4, 4, 5]])

In [90]:
arr.reshape(2, 6)

array([[7, 5, 7, 9, 6, 3],
       [7, 4, 8, 4, 4, 5]])

In [91]:
arr.T

array([[7, 6, 8],
       [5, 3, 4],
       [7, 7, 4],
       [9, 4, 5]])

In [92]:
arr.flatten()

array([7, 5, 7, 9, 6, 3, 7, 4, 8, 4, 4, 5])

In [93]:
arr1 = np.array([1,2,3,4,5])
arr1.ndim

1

In [94]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [95]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4, 5]])

In [96]:
arr

array([[7, 5, 7, 9],
       [6, 3, 7, 4],
       [8, 4, 4, 5]])

In [97]:
arr2 = np.array([[1], [2], [3], [4], [5]])
arr2

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [98]:
# For single element
np.squeeze(arr2)

array([1, 2, 3, 4, 5])

In [99]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [100]:
arr1

array([1, 2, 3, 4, 5])

In [101]:
# Shift by two
np.roll(arr1, 2)

array([4, 5, 1, 2, 3])

In [102]:
# To create diagonal matrix
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Numpy - Binary Operators.

In [103]:
arr1 = np.random.randint(1,10 , (3,4))
arr1

array([[9, 4, 2, 4],
       [8, 5, 7, 8],
       [9, 1, 3, 7]])

In [104]:
arr2 = np.random.randint(1,10 , (3,4))
arr2

array([[6, 4, 1, 1],
       [2, 7, 4, 4],
       [1, 2, 1, 1]])

In [105]:
arr1 + arr2

array([[15,  8,  3,  5],
       [10, 12, 11, 12],
       [10,  3,  4,  8]])

In [106]:
arr1 * arr2

array([[54, 16,  2,  4],
       [16, 35, 28, 32],
       [ 9,  2,  3,  7]])

In [107]:
arr1 / arr2

array([[1.5       , 1.        , 2.        , 4.        ],
       [4.        , 0.71428571, 1.75      , 2.        ],
       [9.        , 0.5       , 3.        , 7.        ]])

In [108]:
arr1 - arr2

array([[ 3,  0,  1,  3],
       [ 6, -2,  3,  4],
       [ 8, -1,  2,  6]])

In [109]:
arr1 % arr2

array([[3, 0, 0, 0],
       [0, 5, 3, 0],
       [0, 1, 0, 0]])

In [110]:
arr1 ** arr2

array([[531441,    256,      2,      4],
       [    64,  78125,   2401,   4096],
       [     9,      1,      3,      7]])

In [111]:
arr1 & arr2

array([[0, 4, 0, 0],
       [0, 5, 4, 0],
       [1, 0, 1, 1]])

In [112]:
arr1 | arr2

array([[15,  4,  3,  5],
       [10,  7,  7, 12],
       [ 9,  3,  3,  7]])

In [113]:
arr1

array([[9, 4, 2, 4],
       [8, 5, 7, 8],
       [9, 1, 3, 7]])

In [114]:
~arr1 

array([[-10,  -5,  -3,  -5],
       [ -9,  -6,  -8,  -9],
       [-10,  -2,  -4,  -8]])

In [115]:
arr1 > arr2

array([[ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

Numpy - String Functions.

In [117]:
arr = np.array(['Shreyash' , "Singh"])
arr

array(['Shreyash', 'Singh'], dtype='<U8')

In [118]:
np.char.upper(arr)

array(['SHREYASH', 'SINGH'], dtype='<U8')

In [119]:
np.char.title(arr)

array(['Shreyash', 'Singh'], dtype='<U8')

In [120]:
np.char.capitalize(arr)

array(['Shreyash', 'Singh'], dtype='<U8')

Numpy - Mathematical Functions.

In [121]:
arr1

array([[9, 4, 2, 4],
       [8, 5, 7, 8],
       [9, 1, 3, 7]])

In [123]:
np.sin(arr1)

array([[ 0.41211849, -0.7568025 ,  0.90929743, -0.7568025 ],
       [ 0.98935825, -0.95892427,  0.6569866 ,  0.98935825],
       [ 0.41211849,  0.84147098,  0.14112001,  0.6569866 ]])

In [124]:
np.cos(arr1)

array([[-0.91113026, -0.65364362, -0.41614684, -0.65364362],
       [-0.14550003,  0.28366219,  0.75390225, -0.14550003],
       [-0.91113026,  0.54030231, -0.9899925 ,  0.75390225]])

In [125]:
np.tan(arr1)

array([[-0.45231566,  1.15782128, -2.18503986,  1.15782128],
       [-6.79971146, -3.38051501,  0.87144798, -6.79971146],
       [-0.45231566,  1.55740772, -0.14254654,  0.87144798]])

In [126]:
np.tanh(arr1)

array([[0.99999997, 0.9993293 , 0.96402758, 0.9993293 ],
       [0.99999977, 0.9999092 , 0.99999834, 0.99999977],
       [0.99999997, 0.76159416, 0.99505475, 0.99999834]])

In [127]:
np.power(arr1, 3)

array([[729,  64,   8,  64],
       [512, 125, 343, 512],
       [729,   1,  27, 343]], dtype=int32)

In [128]:
np.log10(arr1)

array([[0.95424251, 0.60205999, 0.30103   , 0.60205999],
       [0.90308999, 0.69897   , 0.84509804, 0.90308999],
       [0.95424251, 0.        , 0.47712125, 0.84509804]])

In [129]:
np.exp(arr1)

array([[8.10308393e+03, 5.45981500e+01, 7.38905610e+00, 5.45981500e+01],
       [2.98095799e+03, 1.48413159e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.71828183e+00, 2.00855369e+01, 1.09663316e+03]])

In [130]:
np.sqrt(arr1)

array([[3.        , 2.        , 1.41421356, 2.        ],
       [2.82842712, 2.23606798, 2.64575131, 2.82842712],
       [3.        , 1.        , 1.73205081, 2.64575131]])

In [131]:
np.mean(arr1)

5.583333333333333

In [133]:
np.var(arr1)

7.076388888888889

In [134]:
np.median(arr1)

6.0

In [136]:
np.std(arr1)

2.6601482832520613

In [137]:
np.max(arr1)

9

In [138]:
np.min(arr1)

1