Sort, Search & Counting Functions.

In [187]:
import numpy as np

In [188]:
arr = np.array([4, 3, 4, 5, 6, 72, 3, 3, 455, 5, 6, 6])

In [189]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [190]:
np.searchsorted(arr, 34)
# function is used to find the index at which a value should be inserted in a sorted NumPy array 

12

In [191]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [192]:
np.count_nonzero(arr1)

2

In [193]:
np.where(arr > 6)

(array([5, 8], dtype=int64),)

In [194]:
np.extract(arr > 6, arr)

array([ 72, 455])

Numpy - Byte Swapping.

In [195]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [196]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

Numpy - Copies &Views.

In [197]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [198]:
a = np.copy(arr)
# Deep copy

In [199]:
b = arr.view()
# Swallow copy
b = arr

In [200]:
b[0] = 67

In [201]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [202]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

Numpy - Matrix Library.

In [203]:
import numpy.matlib as nm

In [204]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [205]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [206]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Numpy - Linear Algebra

In [207]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [208]:
arr2 = np.random.randint([[5,3] , [2,5]])

In [209]:
nm.dot(arr1, arr2)

array([[0, 2],
       [0, 0]])

In [210]:
arr1 @ arr2

array([[0, 2],
       [0, 0]])